alter table public.leads
  add column if not exists pipeline_stage text not null default 'New'
  check (pipeline_stage in ('New', 'Contacted', 'Qualified', 'Proposal', 'Won', 'Lost'));

create table if not exists public.lead_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lead_id bigint not null references public.leads(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);

create table if not exists public.lead_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lead_id bigint not null references public.leads(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 240),
  due_date date,
  is_complete boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.lead_activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lead_id bigint not null references public.leads(id) on delete cascade,
  kind text not null check (kind in ('created', 'stage_changed', 'note_added', 'task_added', 'task_completed', 'updated')),
  description text not null,
  created_at timestamptz not null default now()
);

alter table public.lead_notes enable row level security;
alter table public.lead_tasks enable row level security;
alter table public.lead_activities enable row level security;

drop policy if exists "Users manage their own lead notes" on public.lead_notes;
create policy "Users manage their own lead notes" on public.lead_notes for all to authenticated
  using (auth.uid() = user_id and exists (select 1 from public.leads where leads.id = lead_notes.lead_id and leads.user_id = auth.uid()))
  with check (auth.uid() = user_id and exists (select 1 from public.leads where leads.id = lead_notes.lead_id and leads.user_id = auth.uid()));

drop policy if exists "Users manage their own lead tasks" on public.lead_tasks;
create policy "Users manage their own lead tasks" on public.lead_tasks for all to authenticated
  using (auth.uid() = user_id and exists (select 1 from public.leads where leads.id = lead_tasks.lead_id and leads.user_id = auth.uid()))
  with check (auth.uid() = user_id and exists (select 1 from public.leads where leads.id = lead_tasks.lead_id and leads.user_id = auth.uid()));

drop policy if exists "Users manage their own lead activities" on public.lead_activities;
create policy "Users manage their own lead activities" on public.lead_activities for all to authenticated
  using (auth.uid() = user_id and exists (select 1 from public.leads where leads.id = lead_activities.lead_id and leads.user_id = auth.uid()))
  with check (auth.uid() = user_id and exists (select 1 from public.leads where leads.id = lead_activities.lead_id and leads.user_id = auth.uid()));

create index if not exists leads_user_stage_idx on public.leads (user_id, pipeline_stage, created_at desc);
create index if not exists lead_notes_lead_idx on public.lead_notes (lead_id, created_at desc);
create index if not exists lead_tasks_lead_idx on public.lead_tasks (lead_id, is_complete, due_date);
create index if not exists lead_activities_lead_idx on public.lead_activities (lead_id, created_at desc);
