create table if not exists public.automation_rules (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  rule_key text not null check (rule_key in ('hot_followup', 'stage_followup', 'overdue_alerts', 'email_suggestions')),
  name text not null,
  description text not null,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  unique (user_id, rule_key)
);

create table if not exists public.automation_runs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lead_id bigint references public.leads(id) on delete cascade,
  rule_key text not null,
  description text not null,
  created_at timestamptz not null default now()
);

alter table public.automation_rules enable row level security;
alter table public.automation_runs enable row level security;

drop policy if exists "Users manage their own automation rules" on public.automation_rules;
create policy "Users manage their own automation rules" on public.automation_rules for all to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage their own automation runs" on public.automation_runs;
create policy "Users manage their own automation runs" on public.automation_runs for all to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists automation_runs_user_idx on public.automation_runs (user_id, created_at desc);
