create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  source text not null,
  budget bigint not null check (budget >= 0),
  timeline text not null,
  property text not null,
  location text not null,
  score integer not null check (score between 0 and 100),
  temperature text not null check (temperature in ('Hot', 'Warm', 'Cold')),
  intent text not null,
  status text not null,
  updated text not null default 'Just now',
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

drop policy if exists "Users can read their own leads" on public.leads;
create policy "Users can read their own leads" on public.leads for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can create their own leads" on public.leads;
create policy "Users can create their own leads" on public.leads for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Users can update their own leads" on public.leads;
create policy "Users can update their own leads" on public.leads for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own leads" on public.leads;
create policy "Users can delete their own leads" on public.leads for delete to authenticated using (auth.uid() = user_id);

create index if not exists leads_user_created_idx on public.leads (user_id, created_at desc);
