create table if not exists public.lead_emails (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lead_id bigint not null references public.leads(id) on delete cascade,
  resend_id text,
  recipient text not null,
  subject text not null check (char_length(subject) between 1 and 240),
  body text not null check (char_length(body) between 1 and 10000),
  status text not null default 'sent' check (status in ('sent', 'delivered', 'bounced', 'failed')),
  created_at timestamptz not null default now()
);

alter table public.lead_emails enable row level security;
drop policy if exists "Users manage their own lead emails" on public.lead_emails;
create policy "Users manage their own lead emails" on public.lead_emails for all to authenticated
  using (auth.uid() = user_id and exists (select 1 from public.leads where leads.id = lead_emails.lead_id and leads.user_id = auth.uid()))
  with check (auth.uid() = user_id and exists (select 1 from public.leads where leads.id = lead_emails.lead_id and leads.user_id = auth.uid()));

create index if not exists lead_emails_lead_idx on public.lead_emails (lead_id, created_at desc);

alter table public.lead_activities drop constraint if exists lead_activities_kind_check;
alter table public.lead_activities add constraint lead_activities_kind_check
  check (kind in ('created', 'stage_changed', 'note_added', 'task_added', 'task_completed', 'updated', 'email_sent'));
